sudo: required
services:
    -   docker
before_install:
    #/  unencrypt the key to access GCP 
    -   openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
    #/  instals the GCP SDK (I dont totally understand the commands)
    -   export CLOUDSDK_CORE_DISABLE_PROMPTS=1
    -   curl https://sdk.cloud.google.com | bash > /dev/null;
    -   source $HOME/google-cloud-sdk/path.bash.inc
    #/  gets the latest version of kubectl
    -   gcloud components update kubectl
    #/  activates unencrypted service account
    -   gcloud auth activate-service-account --key-file service-account.json
    #/  below specifies the project information
    -   gcloud config set project synthetic-song-268620
    -   gcloud config set compute/zone us-central1-a 
    -   gcloud container clusters get-credentials multi-cluster
    #/  logs into docker and builds test container
    -   echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    -   docker build -t barrybt23/react-test -f ./client/Dockerfile.dev ./client
script:
    #/  runs a basic test with proper CI flag
    -   docker run -e CI=true barrybt23/react-test npm run test