apiVersion: cert-manager.io/v1alpha2
kind:   Certificate
metadata:
    name:   sydevops.info-tls
spec:
    secretName: sysdevops.info
    issuerRef:
        name:   letsencrypt-prod
        kind:   ClusterIssuer
    commonName: sysdevops.info
    dndNames:
        -   sysdevops.info
        -   www.sysdevops.info
    acme:
        config:
            -   http01:
                    ingressClass:   nginx
                domains:
                    -   sysdevops.info
                    -   www.sysdevops.info 
    