apiVersion: skaffold/v1
kind:   Config
build:  
    local:
        push: 
    artifacts:
        -   image:  barrybt23/multi-client
            context:    client
            docker:
                dockerfile: Dockerfile.dev
            sync:
                infer:
                    -   '**/*.js'
                    -   '**/*.css'
                    -   '**/*.html'
        -   image:  barrybt23/multi-server
            context:    server
            docker:
                dockerfile: Dockerfile.dev
            sync:
                infer:
                    -   '**/*.js'
        -   image:  barrybt23/multi-worker
            context:    worker
            docker:
                dockerfile: Dockerfile.dev
            sync:
                infer:
                    -   '**/*.js'
deploy:
    kubectl:
        manifests:
            -   k8s-dev/*.yaml
            # -   k8s-dev/client-deployment.yaml
            # -   k8s-dev/server-deployment.yaml
            # -   k8s-dev/worker-deployment.yaml
            # -   k8s-dev/postgres-deployment.yaml
            # -   k8s-dev/redis-deployment.yaml
            # -   k8s-dev/database-persistent-volume-claim.yaml
            # -   k8s-dev/server-cluster-ip-service.yaml
            # -   k8s-dev/client-cluster-ip-service.yaml
            # -   k8s-dev/postgres-cluster-ip-service.yaml
            # -   k8s-dev/redis-cluster-ip-service.yaml
            # -   k8s-dev/ingress-service.yaml
