apiVersion: skaffold/v1beta2
kind:   Config
build:  
    local:
        push:   false
    artifacts:
        -   image:  barrybt23/multi-client
            context:    client
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
                '**/*.css': .
                '**/*.html': .
deploy:
    kubectl:
        manifests:
            -   k8s-dev/client-deployment.yaml
            -   k8s-dev/server-deployment.yaml
            -   k8s-dev/worker-deployment.yaml
            -   k8s-dev/server-cluster-ip-service.yaml
            -   k8s-dev/client-cluster-ip-service.yaml
